version: "3.7"

services:
  vue-app:
    command: >
      sh -c "npm run dev"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oj_fe
    restart: always
    ports:
      - "8899:5173"
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge